### ISSUE TITLE
Task Assignment

### ISSUE THREAD

**Issue by iqbalbasyar** [ComputingTelU/Pelatihan-Python#1]
We need to assign each person's task.
But first we need to complete the [courses](https://www.udemy.com/python-for-data-science-and-machine-learning-bootcamp/learn/v4/t/lecture/5733140?start=750)

**Progress Check**
- [x] Created
- [x] In Progress
- [x] Completed

Please mind to check wether you have completed the courses or not 

| Name | Completed courses  | Kaggle Account
|--------------------|----------|-----|
|@underground-11| completed| [completed](https://www.kaggle.com/underground11) |
|@vayupranaditya|completed|  [completed](https://www.kaggle.com/vayupranaditya)|
|@AlfianR|incomplete|  [completed](https://www.kaggle.com/reverseboy7)|
|@ehardi19|incomplete|  [completed](https://www.kaggle.com/ehardi19)|
|@hanunggulmp|completed|  [completed](https://www.kaggle.com/hanunggulmp)|
|@rizkiar00|completed|  [completed](https://www.kaggle.com/rizkiar)|

**Task Assignment Table**

| Task| Assignee| 
|--------------------------------------------------------------	|---	|
| Python Crash Course                                          	| @vayupranaditya  @ehardi19  @rizkiar00   	|
| Python for Data Analysis : Numpy                             	| @vayupranaditya  @ehardi19  @rizkiar00  	|
| Python for Data Analysis : Pandas                            	|  @AlfianR  @underground-11 	|
| Python for Data Visualization : Matplotlib                   	|  @AlfianR  @hanunggulmp  	|
| Python for Data Visualization : Seaborn                       |   @AlfianR @hanunggulmp     |
| Python for Data Visualization : Plotly, Cufflinks (Optional) 	|   	|
| Python for Data Visualization : Geographical Plotting        	|  @underground-11 	|
| Data Capstone Project</pre>                                  	|   	@underground-11  |

**Comment by vayupranaditya** [comment]
wrong link on vayupranaditya's Kaggle account. It should be [https://www.kaggle.com/vayupranaditya](https://www.kaggle.com/vayupranaditya)

**Comment by iqbalbasyar** [comment]
@vayupranaditya Corrected Thanks

**Comment by ehardi19** [comment]
Kaggle account : https://www.kaggle.com/ehardi19

**Comment by iqbalbasyar** [comment]
@ehardi19 thankyou

**Comment by hanunggulmp** [comment]
kaggle acc: https://www.kaggle.com/hanunggulmp

**Comment by rizkiar00** [comment]
kaggle account: https://www.kaggle.com/rizkiar
